### ISSUE TITLE
Allow folding of subtrees

### ISSUE THREAD

**Issue by bkamins** [SilverDecisions/SilverDecisions#99] opened 2017-03-10 20:49 UTC
It would be useful in large trees to have a folding button - just after the node, where the edges start branching - if the rest of the tree is folded.

It could look like `[+]` when folded (square with `+` inside: standard way to show folding). Folding and unfolding could be placed in context menu, and pressing `[+]` should also unfold.

When the tree is unfolded nothing should be shown (it looks nicer).

Considerations:
1. folding status should be saved and loaded from a savefile
2. The issue might affect proper drawing of the tree, so it should be well thought-over

There is no rush with implementation of this feature.

**Comment by bkamins** [comment] 2017-07-16 12:46
@mwasiluk I would want to have it in 1.0. If it is difficult we will move it beyont 1.0 to unscheduled, so please let me know how you see it.

**Comment by bkamins** [comment] 2017-09-07 17:25
Looks OK.
@pszufe please test it on dev. If you confirm it is OK we can close this issue.

One small issue (but we can leave it as is):
* have a tree with a subtree
* fold a subrtee
* fold whole tree
* unfold while tree

as a result subtree is unfolded.

It is OK for me, but I want to make sure that it was indented - not some kind of bug.

**Comment by mwasiluk** [comment] 2017-09-07 17:32
It was intended

**Comment by bkamins** [comment] 2017-09-23 07:55
@pszufe also text labels introduced by this feature should be translated to all available languages as we have discussed.

**Comment by mwasiluk** [comment] 2017-11-02 21:11
I18n files related with the tree designer are now located in the module sd-tree-designer/src/i18n

**Comment by pszufe** [comment] 2017-11-22 21:12
Tree folding on dev seems to work fine. Closing the issue.

**Closed by pszufe** 2017-11-22 21:12 UTC
Labels: enhancement
